Repository Localitos/pluto, pull requests merged in 2022-11, with the labels that each got.

#170 feat(components): add secondary button variant
  .changeset/sharp-mice-marry.md
  packages/components/src/components/Button/Button.stories.tsx
  packages/components/src/components/Button/Button.tsx
Labels: feature

#188 fix(components): changed background and border input box colors
  .changeset/witty-poets-destroy.md
  packages/components/src/components/InputBox/InputBox.tsx
Labels: bug

#184 feat(components): add ghost button variant
  .changeset/tender-weeks-sell.md
  .jest/jest-setup.ts
  packages/components/src/components/Button/Button.stories.tsx
  packages/components/src/components/Button/Button.test.tsx
  packages/components/src/components/Button/Button.tsx
Labels: feature

#191 Fix/checkbox
  .changeset/three-bottles-sell.md
  packages/components/src/components/Checkbox/Checkbox.tsx
Labels: bug

#193 feat(components): added Modal component
  .changeset/funny-toes-melt.md
  .changeset/silly-terms-drum.md
  package.json
  packages/components/package.json
  packages/components/src/components/Button/Button.tsx
  packages/components/src/components/Modal/Modal.stories.tsx
  packages/components/src/components/Modal/Modal.test.tsx
  packages/components/src/components/Modal/Modal.tsx
  packages/components/src/components/Modal/ModalBody.tsx
  packages/components/src/components/Modal/ModalFooter.tsx
  packages/components/src/components/Modal/ModalHeader.tsx
  packages/components/src/components/Modal/ModalHeading.tsx
  packages/components/src/components/Modal/ModalSubHeading.tsx
  packages/components/src/components/Modal/index.ts
  packages/components/src/index.ts
  packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap
  packages/theme/src/styles/base.tsx
  packages/theme/src/theme/default.ts
  yarn.lock
Labels: feature

#186 feat(components): add file uploader
  .changeset/mighty-goats-yawn.md
  cspell.json
  packages/components/package.json
  packages/components/src/components/FileUploader/CancelUploadButton.tsx
  packages/components/src/components/FileUploader/FileUploader.stories.tsx
  packages/components/src/components/FileUploader/FileUploader.test.tsx
  packages/components/src/components/FileUploader/FileUploader.tsx
  packages/components/src/components/FileUploader/FileUploaderButton.test.tsx
  packages/components/src/components/FileUploader/FileUploaderButton.tsx
  packages/components/src/components/FileUploader/FileUploaderDescription.tsx
  packages/components/src/components/FileUploader/FileUploaderIcon.tsx
  packages/components/src/components/FileUploader/FileUploaderProgressBar.tsx
  packages/components/src/components/FileUploader/FileUploaderTitle.tsx
  packages/components/src/components/FileUploader/RemoveButton.tsx
  packages/components/src/components/FileUploader/index.ts
  packages/components/src/components/FileUploader/types/FileUploaderStatus.ts
  packages/components/src/components/FileUploader/utils/getStatus.test.ts
  packages/components/src/components/FileUploader/utils/getStatus.ts
  packages/components/src/components/HelpText/HelpText.tsx
  packages/components/src/index.ts
  yarn.lock
Labels: feature

#206 feat(components): add extra-large size to Avatar
  .changeset/tall-clouds-happen.md
  packages/components/src/components/Avatar/Avatar.stories.tsx
  packages/components/src/components/Avatar/Avatar.tsx
Labels: feature

#208 fix: [FileUploaderButton] call onClick prop
  .changeset/cool-seas-end.md
  packages/components/src/components/FileUploader/FileUploaderButton.test.tsx
  packages/components/src/components/FileUploader/FileUploaderButton.tsx
Labels: bug

#211 feat(components): add lists and bold to RichText component
  .changeset/purple-garlics-check.md
  packages/components/src/components/List/OrderedList.tsx
  packages/components/src/components/List/UnorderedList.tsx
  packages/components/src/components/RichText/RichText.stories.tsx
  packages/components/src/components/RichText/RichText.tsx
Labels: feature

#213 feat(theme): add new colorBackgroundBodyStrong bg color to theme
  .changeset/shy-peaches-grow.md
  packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap
  packages/theme/src/theme/default.ts
Labels: feature

#210 feat(tokens): add new background colors to the default theme
  .changeset/spicy-zebras-dream.md
  packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap
  packages/theme/src/theme/default.ts
Labels: feature

#207 feat(components): added TextArea component
  .changeset/orange-turtles-fetch.md
  packages/components/src/components/Input/Input.tsx
  packages/components/src/components/Textarea/Textarea.stories.tsx
  packages/components/src/components/Textarea/Textarea.test.tsx
  packages/components/src/components/Textarea/Textarea.tsx
  packages/components/src/components/Textarea/index.ts
  packages/components/src/index.ts
Labels: feature

#219 fix(components): add new Button variant
  .changeset/sharp-bears-rescue.md
  packages/components/src/components/Button/Button.stories.tsx
  packages/components/src/components/Button/Button.tsx
Labels: feature

#225 fix(components): adjust button height on file uploader
  .changeset/cuddly-kangaroos-pull.md
  packages/components/src/components/FileUploader/FileUploader.stories.tsx
  packages/components/src/components/FileUploader/FileUploader.tsx
Labels: bug

#227 fix(components): add rel and target as props on the button
  .changeset/poor-hornets-cheer.md
  packages/components/src/components/Button/Button.tsx
Labels: bug

#221 feat(components): add Tooltip component
  .changeset/late-eels-protect.md
  packages/components/src/components/Modal/Modal.stories.tsx
  packages/components/src/components/Tooltip/Tooltip.stories.tsx
  packages/components/src/components/Tooltip/Tooltip.test.tsx
  packages/components/src/components/Tooltip/Tooltip.tsx
  packages/components/src/components/Tooltip/index.ts
  packages/components/src/index.ts
Labels: feature

#216 Fix/checkbox
  .changeset/eleven-rice-mate.md
  packages/components/src/components/Checkbox/Checkbox.stories.tsx
  packages/components/src/components/Checkbox/Checkbox.tsx
Labels: bug

#234 feat(components): update file uploader description text color
  .changeset/eighty-rings-serve.md
  packages/components/src/components/FileUploader/FileUploaderDescription.tsx
Labels: feature

#235 Feat/richtext
  .changeset/thirty-timers-knock.md
  packages/components/src/components/RichText/RichText.stories.tsx
  packages/components/src/components/RichText/RichText.tsx
Labels: feature

#239 fix(components): fix dropzone export
  .changeset/fuzzy-pans-behave.md
  packages/components/src/index.ts
Labels: bug

#241 fix(components): omit noonce from ariakit props
  .changeset/dull-apples-relate.md
  cspell.json
  packages/components/src/components/Modal/Modal.stories.tsx
  packages/components/src/components/Modal/Modal.tsx
  packages/components/src/components/Tooltip/Tooltip.tsx
Labels: bug

#255 chore(components): add disableOverflow prop to ModalBody
  .changeset/sharp-brooms-run.md
  packages/components/src/components/Modal/Modal.stories.tsx
  packages/components/src/components/Modal/ModalBody.tsx
Labels: chore

#256 fix(components): dynamic file restriction texts for Dropzone
  .changeset/fluffy-monkeys-jog.md
  packages/components/src/components/Dropzone/Dropzone.stories.tsx
  packages/components/src/components/Dropzone/Dropzone.test.tsx
  packages/components/src/components/Dropzone/Dropzone.tsx
  packages/components/src/components/Dropzone/getFileRestrictionText.test.ts
  packages/components/src/components/Dropzone/getFileRestrictionText.ts
Labels: bug
