Repository Localitos/pluto, pull requests merged in 2022-10, with the labels that each got.

#77 chore(theme): export createGlobalStyle from xStyled
  .changeset/plenty-tables-appear.md
  packages/theme/src/index.ts
Labels: chore

#79 fix(theme): added types to export and correct peerDeps
  .changeset/pink-cups-sniff.md
  .changeset/plenty-guests-drop.md
  packages/components/package.json
  packages/theme/package.json
  packages/theme/src/index.ts
Labels: bug

#95 chore: update readme with theme provider info
  README.md
Labels: chore

#97 feat(components): add table component
  .changeset/giant-stingrays-trade.md
  package.json
  packages/components/src/components/Button/Button.tsx
  packages/components/src/components/Table/TBody.tsx
  packages/components/src/components/Table/THead.tsx
  packages/components/src/components/Table/Table.stories.tsx
  packages/components/src/components/Table/Table.test.tsx
  packages/components/src/components/Table/Table.tsx
  packages/components/src/components/Table/Td.tsx
  packages/components/src/components/Table/Th.tsx
  packages/components/src/components/Table/Tr.tsx
  packages/components/src/components/Table/index.ts
  packages/components/src/index.ts
  yarn.lock
Labels: feature

#100 feat: add icon to primary button
  .changeset/late-mirrors-agree.md
  .changeset/wicked-needles-hang.md
  packages/components/src/components/Button/Button.stories.tsx
  packages/components/src/components/Button/Button.test.tsx
  packages/components/src/components/Button/Button.tsx
  packages/components/src/index.ts
Labels: feature

#110 chore: use react 17
  .changeset/tidy-bottles-repair.md
  package.json
  packages/components/package.json
  packages/components/src/components/Callout/Callout.test.tsx
  packages/components/src/components/Callout/Callout.tsx
  packages/theme/package.json
  yarn.lock
Labels: chore

#112 chore: move deps to peer and dev deps
  .changeset/eight-donkeys-teach.md
  packages/components/package.json
  packages/theme/package.json
Labels: bug

#116 fix: update theme peer dependecies version
  .changeset/grumpy-actors-judge.md
  packages/theme/package.json
Labels: bug

#118 feat(components): add anchor
  .changeset/fluffy-cougars-thank.md
  .changeset/wise-steaks-burn.md
  packages/components/src/components/Anchor/Anchor.stories.tsx
  packages/components/src/components/Anchor/Anchor.test.tsx
  packages/components/src/components/Anchor/Anchor.tsx
  packages/components/src/components/Anchor/index.ts
  packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap
  packages/theme/src/theme/default.ts
Labels: feature

#93 feat(components): add avatar
  .changeset/giant-guests-allow.md
  .changeset/ninety-pumas-shake.md
  packages/components/package.json
  packages/components/src/components/Avatar/Avatar.stories.tsx
  packages/components/src/components/Avatar/Avatar.test.tsx
  packages/components/src/components/Avatar/Avatar.tsx
  packages/components/src/components/Avatar/getImageOrientation.test.ts
  packages/components/src/components/Avatar/getImageOrientation.ts
  packages/components/src/components/Avatar/getInitials.test.ts
  packages/components/src/components/Avatar/getInitials.ts
  packages/components/src/components/Avatar/index.ts
  packages/components/src/components/Avatar/useGetImageOrientation.test.ts
  packages/components/src/components/Avatar/useGetImageOrientation.ts
  packages/components/src/index.ts
  packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap
  packages/theme/src/theme/default.ts
  public/images/profile.jpg
  yarn.lock
Labels: feature

#119 feat(components): add RichText component
  .changeset/silent-crabs-turn.md
  packages/components/package.json
  packages/components/src/components/RichText/RichText.stories.tsx
  packages/components/src/components/RichText/RichText.test.tsx
  packages/components/src/components/RichText/RichText.tsx
  packages/components/src/components/RichText/index.ts
  packages/components/src/index.ts
  yarn.lock
Labels: feature

#122 fix(components): make anchor component public
  .changeset/good-spiders-search.md
  packages/components/src/index.ts
Labels: bug

#125 feat(theme): add new background color tokens
  .changeset/spicy-avocados-lay.md
  packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap
  packages/theme/src/theme/default.ts
Labels: feature

#129 feat(components): add sticky header and top props to table header
  .changeset/cool-eagles-smoke.md
  packages/components/src/components/Table/THead.tsx
  packages/components/src/components/Table/Table.stories.tsx
Labels: feature

#148 feat(components): add color to heading component
  .changeset/clean-planes-pretend.md
  .changeset/great-dryers-promise.md
  packages/components/src/components/Heading/Heading.tsx
  packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap
  packages/theme/src/theme/default.ts
Labels: feature

#150 feat(components): allow breakpoints in heading size
  .changeset/fair-bobcats-repeat.md
  packages/components/src/components/Heading/Heading.stories.tsx
  packages/components/src/components/Heading/Heading.tsx
Labels: feature

#152 fix(components): update callout padding
  .changeset/healthy-moles-study.md
  packages/components/src/components/Callout/Callout.tsx
Labels: feature

#126 feat(components): add badge
  .changeset/swift-moose-deny.md
  .changeset/tame-suns-unite.md
  packages/components/src/components/Badge/Badge.stories.tsx
  packages/components/src/components/Badge/Badge.test.tsx
  packages/components/src/components/Badge/Badge.tsx
  packages/components/src/components/Badge/index.ts
  packages/components/src/index.ts
  packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap
  packages/theme/src/theme/default.ts
Labels: feature

#156 fix(components): adjust small button sizes
  .changeset/hip-queens-double.md
  packages/components/src/components/Button/Button.tsx
Labels: bug

#158 feat(design-tokens): add design tokens package
  .changeset/curly-chefs-poke.md
  packages/design-tokens/.eslintrc.js
  packages/design-tokens/README.md
  packages/design-tokens/config.json
  packages/design-tokens/jest.config.js
  packages/design-tokens/package.json
  packages/design-tokens/src/tokens/border-radius.tokens.json
  packages/design-tokens/src/tokens/border-style.tokens.json
  packages/design-tokens/src/tokens/border-width.tokens.json
  packages/design-tokens/src/tokens/color.tokens.json
  packages/design-tokens/src/tokens/font-family.tokens.json
  packages/design-tokens/src/tokens/font-size.tokens.json
  packages/design-tokens/src/tokens/font-weight.tokens.json
  packages/design-tokens/src/tokens/line-height.tokens.json
  packages/design-tokens/src/tokens/size.tokens.json
  packages/design-tokens/src/tokens/space.tokens.json
  packages/design-tokens/src/tokens/zindex.tokens.json
  packages/design-tokens/tsconfig.json
  yarn.lock
Labels: feature

#161 feat(components): add type datetime-local to input type
  .changeset/heavy-clouds-remain.md
  packages/components/src/components/Input/Input.tsx
  packages/components/src/components/InputBox/InputBox.tsx
Labels: feature

#155 feat(components): add button text variant
  .changeset/hip-parents-obey.md
  packages/components/src/components/Button/Button.stories.tsx
  packages/components/src/components/Button/Button.tsx
Labels: feature

#159 feat(components): add input leading and trailing icons
  .changeset/large-baboons-dress.md
  packages/components/src/components/Input/Input.stories.tsx
  packages/components/src/components/Input/Input.tsx
  packages/components/src/components/InputBox/InputBox.tsx
Labels: feature

#165 feat(components): add search input component
  .changeset/mighty-melons-breathe.md
  packages/components/src/components/Search/Search.stories.tsx
  packages/components/src/components/Search/Search.test.tsx
  packages/components/src/components/Search/Search.tsx
  packages/components/src/components/Search/index.ts
  packages/components/src/index.ts
Labels: feature
