Repository Localitos/pluto, pull requests merged in 2022-09, with the labels that each got.

#20 [TREX-7] chore: add codeowners file
  .github/CODEOWNERS
  cspell.json
Labels: chore

#18 [TREX-3] feat: merged tsconfig from backend repo
  package-lock.json
  packages/components/package.json
  packages/components/tsconfig.json
  packages/components/tsconfig.lib.json
  packages/components/tsconfig.test.json
  packages/tsconfig/package.json
  packages/tsconfig/tsconfig.json
  tsconfig.json
Labels: feature

#24 feat: added gh issues template
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: feature

#23 feat: add new changesets config
  .changeset/README.md
  .changeset/config.json
  .github/workflows/on_release_publish.yml
  CONTRIBUTING.md
  package.json
Labels: feature

#26 fix: Add path packages to Release action
  .github/workflows/on_release_publish.yml
  packages/components/package.json
  packages/eslint-config/package.json
  packages/theme/package.json
  packages/tsconfig/package.json
Labels: chore

#27 fix: add commit message to release
  .github/workflows/on_release_publish.yml
Labels: bug

#30 feat: add github action to assign owner to PR
  .github/workflows/auto_assign_owner.yml
  cspell.json
Labels: feature

#28 feat(components): add text primitive component
  .changeset/wise-spies-leave.md
  cspell.json
  packages/components/src/index.ts
  packages/components/src/primitives/Box/BaseBox.tsx
  packages/components/src/primitives/Text/BaseText.tsx
  packages/components/src/primitives/Text/Text.stories.tsx
  packages/components/src/primitives/Text/Text.test.tsx
  packages/components/src/primitives/Text/Text.tsx
  packages/components/src/primitives/Text/index.ts
Labels: feature

#33 chore: add font section to readme
  README.md
  cspell.json
Labels: chore

#34 chore: clean up storybook and use docs
  .storybook/preview.js
  package.json
  yarn.lock
Labels: chore

#35 build: send a message to Slack after publishing
  .github/workflows/on_release_publish.yml
Labels: enhancement

#31 feat: setup chromatic to Pluto
  .github/workflows/visual_regression_tests.yml
  .gitignore
  cspell.json
  package.json
Labels: feature

#36 chore: update turborepo, change scripts
  package.json
  yarn.lock
Labels: chore

#38 chore: add dependabot config
  .github/dependabot.yml
Labels: chore

#50 chore: remove dependabot branchs from visual regression tests action
  .github/workflows/visual_regression_tests.yml
Labels: chore

#52 fix: dependabot pattern on vrt action
  .github/workflows/visual_regression_tests.yml
Labels: chore

#54 chore: remove netlify from build
  README.md
Labels: chore

#55 chore: avoid running vrt on dependabot prs
  .github/workflows/visual_regression_tests.yml
Labels: chore

#39 chore: add dangerjs
  .github/workflows/on_pull_request.yml
  .gitignore
  dangerfile.ts
  package.json
  yarn.lock
Labels: chore

#56 fix: dependabot name on vrt action
  .github/workflows/visual_regression_tests.yml
Labels: bug

#58 fix: dependabot
  .github/workflows/visual_regression_tests.yml
Labels: bug

#59 fix: update if conditional on vrt action
  .github/workflows/visual_regression_tests.yml
Labels: bug

#60 fix: avoid running danger for dependabot and draft PRs
  .github/workflows/on_pull_request.yml
Labels: bug
