Repository Localitos/pluto, pull requests merged in 2022-12, with the labels that each got.

#269 chore: add contributing link to readme
  README.md
Labels: chore

#270 chore: setup kodiak config
  .github/pr-labeler-config.yml
  .kodiak.toml
Labels: chore

#271 Version Packages
  .changeset/dry-dolphins-jump.md
  .changeset/popular-terms-tease.md
  .changeset/real-mirrors-lay.md
  .changeset/silent-bugs-dress.md
  .changeset/warm-comics-wonder.md
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/design-tokens/CHANGELOG.md
  packages/design-tokens/package.json
  packages/theme/CHANGELOG.md
  packages/theme/package.json
Labels: :rocket: merge it!

#275 chore(components): add heading mobile chromatic story
  .changeset/dry-bobcats-doubt.md
  packages/components/src/components/Heading/Heading.stories.tsx
Labels: chore, :rocket: merge it!

#302 feat(components): add height, color and radius to progress bar
  .changeset/dull-horses-return.md
  packages/components/src/components/ProgressBar/ProgressBar.stories.tsx
  packages/components/src/components/ProgressBar/ProgressBar.test.tsx
  packages/components/src/components/ProgressBar/ProgressBar.tsx
Labels: feature

#304 fix(components): replace progress bar height with size variant
  .changeset/healthy-guests-marry.md
  packages/components/src/components/ProgressBar/ProgressBar.stories.tsx
  packages/components/src/components/ProgressBar/ProgressBar.test.tsx
  packages/components/src/components/ProgressBar/ProgressBar.tsx
Labels: bug

#308 fix(components): add icon alignment and display
  .changeset/yellow-houses-kick.md
  packages/components/src/components/Icon/Icon.tsx
Labels: bug

#315 chore: add code reviewers github action
  .github/CODEOWNERS
  .kodiak.toml
Labels: chore, Merge It

#317 chore: correct kodiak version
  .github/dependabot.yml
  .kodiak.toml
Labels: chore

#316 Version Packages
  .changeset/seven-radios-talk.md
  .changeset/sixty-apples-kick.md
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/theme/CHANGELOG.md
  packages/theme/package.json
Labels: automerge

#326 feat(components): add Toast component
  .changeset/thin-colts-appear.md
  packages/components/package.json
  packages/components/src/components/Toast/Toast.stories.tsx
  packages/components/src/components/Toast/Toast.test.tsx
  packages/components/src/components/Toast/Toast.tsx
  packages/components/src/components/Toast/ToastViewport.tsx
  packages/components/src/components/Toast/index.ts
  packages/components/src/components/Toast/types.ts
  packages/components/src/index.ts
  yarn.lock
Labels: feature

#328 Version Packages
  .changeset/thin-colts-appear.md
  packages/components/CHANGELOG.md
  packages/components/package.json
Labels: automerge

#331 fix(components): add missing label to select items
  .changeset/curly-kids-love.md
  packages/components/src/components/Select/Select.stories.tsx
  packages/components/src/components/Select/Select.test.tsx
  packages/components/src/components/Select/Select.tsx
  packages/components/src/components/Select/SelectItem.tsx
Labels: bug, automerge

#333 fix(components): correct the starts with error for initial
  .changeset/itchy-seals-explode.md
  packages/components/src/components/Select/Select.tsx
Labels: bug

#332 Version Packages
  .changeset/curly-kids-love.md
  .changeset/itchy-seals-explode.md
  packages/components/CHANGELOG.md
  packages/components/package.json
Labels: automerge

#336 feat(components): added multiselect ability to select
  .changeset/tricky-dots-hide.md
  packages/components/src/components/Select/Select.stories.tsx
  packages/components/src/components/Select/Select.test.tsx
  packages/components/src/components/Select/Select.tsx
  packages/components/src/components/Select/SelectItem.tsx
Labels: feature, automerge

#338 feat(components): added destructive button variant
  .changeset/grumpy-birds-listen.md
  packages/components/src/components/Button/Button.stories.tsx
  packages/components/src/components/Button/Button.tsx
Labels: feature, automerge

#337 Version Packages
  .changeset/grumpy-birds-listen.md
  .changeset/tricky-dots-hide.md
  packages/components/CHANGELOG.md
  packages/components/package.json
Labels: automerge

#339 chore(components): export SelectItemProps
  .changeset/blue-kings-fix.md
  packages/components/src/components/Select/index.ts
Labels: chore, automerge

#340 Version Packages
  .changeset/blue-kings-fix.md
  packages/components/CHANGELOG.md
  packages/components/package.json
Labels: automerge

#360 feat(components): added useToast hook and ToastContainer
  .changeset/poor-buttons-joke.md
  packages/components/src/components/Toast/Toast.stories.tsx
  packages/components/src/components/Toast/Toast.test.tsx
  packages/components/src/components/Toast/Toast.tsx
  packages/components/src/components/Toast/ToastContainer.tsx
  packages/components/src/components/Toast/ToastContext.tsx
  packages/components/src/components/Toast/ToastViewport.tsx
  packages/components/src/components/Toast/index.ts
  packages/components/src/components/Toast/types.ts
  packages/components/src/components/Toast/useToast.tsx
Labels: feature
