Repository Localitos/pluto, pull requests merged in 2023-01, with the labels that each got.

#381 feat(components): added StepIndicator component
  .changeset/beige-cycles-buy.md
  packages/components/src/components/Input/Input.stories.tsx
  packages/components/src/components/StepIndicator/StepIndicator.stories.tsx
  packages/components/src/components/StepIndicator/StepIndicator.test.tsx
  packages/components/src/components/StepIndicator/StepIndicator.tsx
  packages/components/src/components/StepIndicator/StepIndicatorSegment.tsx
  packages/components/src/components/StepIndicator/index.ts
  packages/components/src/index.ts
Labels: feature, automerge

#385 feat: add new borderRadius tokens
  .changeset/lemon-zoos-draw.md
  packages/design-tokens/src/tokens/border-radius.tokens.json
  packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap
Labels: feature

#389 Version Packages
  .changeset/nasty-experts-divide.md
  .changeset/weak-bears-wonder.md
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/theme/CHANGELOG.md
  packages/theme/package.json
Labels: automerge

#402 fix(components): added cursor pointer to dropzone
  .changeset/silver-beans-switch.md
  packages/components/src/components/Dropzone/Dropzone.tsx
Labels: bug

#403 Version Packages
  .changeset/silver-beans-switch.md
  packages/components/CHANGELOG.md
  packages/components/package.json
Labels: automerge

#405 fix(components): allow anchor and button to work as link
  .changeset/dirty-pianos-glow.md
  .eslintrc.js
  .storybook/main.js
  .storybook/manager.js
  .storybook/preview.js
  .storybook/theme.js
  cspell.json
  package.json
  packages/components/src/components/Anchor/Anchor.stories.tsx
  packages/components/src/components/Anchor/Anchor.tsx
  packages/components/src/components/Button/Button.stories.tsx
  packages/components/src/components/Button/Button.tsx
  packages/components/src/components/Tabs/Tabs.stories.tsx
  yarn.lock
Labels: bug

#408 Version Packages
  .changeset/four-coats-sip.md
  .changeset/hungry-forks-live.md
  .changeset/ninety-turtles-thank.md
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/design-tokens/CHANGELOG.md
  packages/design-tokens/package.json
  packages/theme/CHANGELOG.md
  packages/theme/package.json
Labels: automerge

#436 fix(components): fix heading text-transform style
  .changeset/chatty-roses-change.md
  packages/components/src/components/Heading/Heading.tsx
Labels: bug

#438 feat(components): added FormInput component
  .changeset/lemon-zebras-admire.md
  packages/components/src/components/FormInput/FormInput.stories.tsx
  packages/components/src/components/FormInput/FormInput.test.tsx
  packages/components/src/components/FormInput/FormInput.tsx
  packages/components/src/components/FormInput/index.ts
  packages/components/src/index.ts
Labels: feature

#444 fix(components): removed absolute positioning of helptext
  .changeset/real-mice-remain.md
  packages/components/src/components/FormInput/FormInput.tsx
  packages/components/src/components/FormSelect/FormSelect.stories.tsx
  packages/components/src/components/FormSelect/FormSelect.tsx
  packages/components/src/components/FormTextArea/FormTextArea.tsx
Labels: bug, automerge

#446 feat(components): added bordered and textAlign to table
  .changeset/many-papayas-jog.md
  packages/components/src/components/StepIndicator/StepIndicator.stories.tsx
  packages/components/src/components/StepIndicator/StepIndicator.tsx
  packages/components/src/components/StepIndicator/StepIndicatorSegment.tsx
  packages/components/src/components/Table/Table.stories.tsx
  packages/components/src/components/Table/Table.tsx
  packages/components/src/components/Table/TableContext.tsx
  packages/components/src/components/Table/Td.tsx
  packages/components/src/components/Table/Th.tsx
Labels: bug, feature

#447 Version Packages
  .changeset/many-papayas-jog.md
  packages/components/CHANGELOG.md
  packages/components/package.json
Labels: automerge

#450 feat(components): add ControlledFormInput for react hook form
  .changeset/eighty-laws-join.md
  package.json
  packages/components/src/components/FormInput/ControlledFormInput.tsx
  packages/components/src/components/FormInput/FormInput.stories.tsx
  packages/components/src/components/FormInput/FormInput.test.tsx
  packages/components/src/components/FormInput/FormInput.tsx
  packages/components/src/components/FormInput/index.ts
  packages/components/src/components/Input/Input.tsx
  yarn.lock
Labels: feature

#477 fix(components): added spacing to list items
  .changeset/long-lobsters-study.md
  packages/components/src/components/List/ListItem.tsx
Labels: bug

#478 Version Packages
  .changeset/eighty-laws-join.md
  .changeset/long-lobsters-study.md
  packages/components/CHANGELOG.md
  packages/components/package.json
Labels: automerge

#479 feat(components): add ControlledFormTextArea for react hook form
  .changeset/healthy-walls-sparkle.md
  packages/components/src/components/FormTextArea/ControlledFormTextArea.tsx
  packages/components/src/components/FormTextArea/FormTextArea.stories.tsx
  packages/components/src/components/FormTextArea/FormTextArea.test.tsx
  packages/components/src/components/FormTextArea/FormTextArea.tsx
  packages/components/src/components/FormTextArea/index.ts
Labels: feature, automerge

#480 Version Packages
  .changeset/healthy-walls-sparkle.md
  packages/components/CHANGELOG.md
  packages/components/package.json
Labels: automerge
