Repository Localitos/pluto, pull requests merged in 2024-04, with the labels that each got.

#1484 feat: add backdrop to drawer component
  .changeset/red-chefs-sin.md
  packages/components/src/components/Drawer/Drawer.stories.tsx
  packages/components/src/components/Drawer/Drawer.tsx
Labels: feature

#1488 feat: add transition to drawer component
  .changeset/rotten-ravens-nail.md
  packages/components/src/components/Drawer/Drawer.test.tsx
  packages/components/src/components/Drawer/Drawer.tsx
Labels: feature

#1525 fix(components): Add transparent background for PaginationButton
  .changeset/small-hounds-destroy.md
  packages/components/src/components/Pagination/Pagination.stories.tsx
  packages/components/src/components/Pagination/PaginationButton.tsx
Labels: bug

#1514 fix: show entire drawer body using full height
  .changeset/tame-fans-fly.md
  packages/components/src/components/Drawer/DrawerBody.tsx
Labels: bug

#926 chore: replace ariakit with @ariakit-react
  .changeset/two-trees-tickle.md
  packages/components/package.json
  packages/components/src/components/ConfirmationModal/ConfirmationModal.stories.tsx
  packages/components/src/components/ConfirmationModal/ConfirmationModal.test.tsx
  packages/components/src/components/ConfirmationModal/ConfirmationModal.tsx
  packages/components/src/components/Drawer/Drawer.stories.tsx
  packages/components/src/components/Drawer/Drawer.test.tsx
  packages/components/src/components/Drawer/Drawer.tsx
  packages/components/src/components/Drawer/DrawerHeader.tsx
  packages/components/src/components/Drawer/index.ts
  packages/components/src/components/FormSelect/FormSelect.test.tsx
  packages/components/src/components/Menu/Menu.test.tsx
  packages/components/src/components/Menu/Menu.tsx
  packages/components/src/components/Modal/Modal.stories.tsx
  packages/components/src/components/Modal/Modal.test.tsx
  packages/components/src/components/Modal/Modal.tsx
  packages/components/src/components/Modal/ModalHeader.tsx
  packages/components/src/components/Modal/index.ts
  packages/components/src/components/Select/Select.test.tsx
  packages/components/src/components/Select/Select.tsx
  packages/components/src/components/Select/SelectItem.tsx
  packages/components/src/components/Select/SelectPopover.tsx
  packages/components/src/components/StepIndicator/StepIndicatorSegment.tsx
  packages/components/src/components/Tabs/Tab.tsx
  packages/components/src/components/Tabs/TabList.tsx
  packages/components/src/components/Tabs/TabPanel.tsx
  packages/components/src/components/Tabs/Tabs.test.tsx
  packages/components/src/components/Tabs/Tabs.tsx
  packages/components/src/components/Tabs/TabsContext.tsx
  packages/components/src/components/Tabs/index.ts
  packages/components/src/components/Tooltip/Tooltip.stories.tsx
  packages/components/src/components/Tooltip/Tooltip.test.tsx
  packages/components/src/components/Tooltip/Tooltip.tsx
  packages/components/src/components/Tooltip/index.ts
  yarn.lock
Labels: chore
