Repository Localitos/pluto, pull requests merged in 2024-03, with the labels that each got.

#1355 feat(components): add red variant for badge
  .changeset/itchy-cows-hunt.md
  packages/components/src/components/Badge/Badge.stories.tsx
  packages/components/src/components/Badge/Badge.tsx
Labels: feature

#1360 fix: update overflow in table
  .changeset/eighty-buses-speak.md
  packages/components/src/components/Table/Table.tsx
Labels: bug

#1362 fix: table row hover when it is not clickable
  .changeset/poor-penguins-vanish.md
  packages/components/src/components/Table/Tr.tsx
Labels: bug

#1364 feat: improve how image and content are split
  .changeset/heavy-paws-perform.md
  packages/components/src/components/ContentCard/ContentCard.tsx
Labels: feature

#1378 Add `flexed` option to `Tabs` component
  .changeset/rare-candles-mix.md
  packages/components/src/components/Tabs/Tabs.stories.tsx
  packages/components/src/components/Tabs/Tabs.tsx
Labels: feature

#1385 feat: add isHoverable prop to table row
  .changeset/brave-oranges-lie.md
  packages/components/src/components/Table/Table.stories.tsx
  packages/components/src/components/Table/Tr.tsx
Labels: feature

#1407 Add color prefix tokens to colors
  .changeset/violet-rivers-cry.md
  packages/design-tokens/config.js
  packages/design-tokens/src/tokens/color.tokens.json
  packages/theme/src/__tests__/__snapshots__/theme.test.tsx.snap
Labels: chore

#1411 feat: Enable prefixes for multiple tokens on docs
  .changeset/seven-trains-judge.md
  packages/design-tokens/docs/borders.mdx
  packages/design-tokens/docs/colors.mdx
  packages/design-tokens/docs/components/TokensTable.tsx
  packages/design-tokens/docs/components/constants.tsx
  packages/design-tokens/docs/components/createPreview.tsx
  packages/design-tokens/docs/font-sizes.mdx
  packages/design-tokens/docs/font-weights.mdx
  packages/design-tokens/docs/icon-sizes.mdx
  packages/design-tokens/docs/spacing.mdx
  packages/design-tokens/docs/types/TokenTuple.ts
  packages/design-tokens/docs/utils/buildTokensTableRows.tsx
  packages/design-tokens/docs/utils/getTokenComment.ts
  packages/design-tokens/docs/utils/getTokenName.tsx
  packages/design-tokens/docs/utils/getTokenValue.ts
Labels: feature

#1413 feat: implement Utility Card
  .changeset/mean-pigs-attack.md
  packages/components/src/components/UtilityCard/UtilityCard.stories.tsx
  packages/components/src/components/UtilityCard/UtilityCard.test.tsx
  packages/components/src/components/UtilityCard/UtilityCard.tsx
  packages/components/src/components/UtilityCard/index.ts
Labels: enhancement, feature
