Repository Localitos/pluto, pull requests merged in 2024-02, with the labels that each got.

#1275 Version Packages
  .changeset/spicy-elephants-bow.md
  packages/components/CHANGELOG.md
  packages/components/package.json
Labels: automerge

#1338 fix: [ContentCard] remove spaces when image does not fit container
  .changeset/dull-moose-fly.md
  packages/components/src/components/ContentCard/ContentCard.tsx
Labels: bug

#1339 Version Packages
  .changeset/dull-moose-fly.md
  .changeset/eight-dryers-judge.md
  packages/components/CHANGELOG.md
  packages/components/package.json
  packages/design-tokens/CHANGELOG.md
  packages/design-tokens/package.json
  packages/theme/CHANGELOG.md
  packages/theme/package.json
Labels: automerge

#1351 feat: add border and background color white to Table component
  .changeset/six-pants-provide.md
  packages/components/src/components/Table/Table.tsx
Labels: feature
